spring:
  application:
    name: github-issue-service

github:
  url: https://api.github.com

webhook:
  url: https://webhook.site/d2adea52-4308-4bee-aeef-cb2f87f89307

resilience4j:
  retry:
    instances:
      githubRetry:
        maxAttempts: 3
        waitDuration: 2s
      webhookRetry:
        maxAttempts: 3
        waitDuration: 2s

logging:
  level:
    root: INFO
    com.seuprojeto: DEBUG