spring:
  application:
    name: github-issue-service

github:
  url: https://api.github.com

webhook:
  url: https://webhook.site/ce3bd36b-e4c3-4e6f-b88a-d7c787e05711

resilience4j:
  retry:
    instances:
      githubRetry:
        maxAttempts: 3
        waitDuration: 2s
      webhookRetry:
        maxAttempts: 3
        waitDuration: 2s
  circuitbreaker:
    instances:
      githubCircuitBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      webhookCircuitBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

logging:
  level:
    root: INFO
    com.seuprojeto: DEBUG